language: perl
sudo: false
perl:
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
dist: trusty
cache:
    directories:
        - local
before_install:
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm Carton
install:
    - carton install
    - perl -MExtUtils::Manifest -e 'ExtUtils::Manifest::mkmanifest()'
before_script:
    # bugfix for trusty(Ubuntu 14.04)
    - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
script:
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t|^xt/" carton exec -- prove -lvr t xt addons/*/t
after_success:
    - carton exec -- cover -report coveralls
