language: perl
sudo: false
perl:
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
cache:
    directories:
        - local
before_install:
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm Carton
install:
    - carton install
script:
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t|^xt/" carton exec -- prove -lvr t xt addons/*/t
after_success:
    - carton exec -- cover -report coveralls
