name="Markets"
module_maker="ModuleBuild"
badges=['travis', 'coveralls']

[build]
    build_class = "devel::builder::MyBuilder"

[release]
    do_not_upload_to_cpan = true

[FileGatherer]
    include_dotfiles = true

[tap_harness_args]
    verbosity = 1
    color = true
