(
    'AddressContinent' => [
        [qw/id position name/],
        [ '1', '1', 'Americas' ],
        [ '2', '2', 'Asia Pacific' ],
        [ '3', '3', 'Europe' ],
        [ '4', '4', 'Africa' ],
    ],

    # ISO 3166-1 alpha-2 code and english name
    'AddressCountry' => [
        [qw/code group_id position name/],
        [ 'AF', '2', '1', 'Afghanistan' ],
        [ 'AX', '3', '2', 'Åland Islands' ],
        [ 'AL', '3', '3', 'Albania' ],
        [ 'DZ', '4', '4', 'Algeria' ],
        [ 'AS', '2', '5', 'American Samoa' ],
        [ 'AD', '3', '6', 'Andorra' ],
        [ 'AO', '4', '7', 'Angola' ],
        [ 'AI', '1', '8', 'Anguilla' ],
        # [ 'AQ', '', '9', 'Antarctica' ], # 南極
        [ 'AG', '1', '10', 'Antigua and Barbuda' ],
        [ 'AR', '1', '11', 'Argentina' ],
        [ 'AM', '2', '12', 'Armenia' ], # NOTE: 3
        [ 'AW', '1', '13', 'Aruba' ],
        [ 'AU', '2', '14', 'Australia' ],
        [ 'AT', '3', '15', 'Austria' ],
        [ 'AZ', '2', '16', 'Azerbaijan' ], # NOTE: 3
        [ 'BS', '1', '17', 'Bahamas' ],
        [ 'BH', '2', '18', 'Bahrain' ],
        [ 'BD', '2', '19', 'Bangladesh' ],
        [ 'BB', '1', '20', 'Barbados' ],
        [ 'BY', '3', '21', 'Belarus' ],
        [ 'BE', '3', '22', 'Belgium' ],
        [ 'BZ', '1', '23', 'Belize' ],
        [ 'BJ', '4', '24', 'Benin' ],
        [ 'BM', '1', '25', 'Bermuda' ],
        [ 'BT', '2', '26', 'Bhutan' ],
        [ 'BO', '1', '27', 'Bolivia' ],
        [ 'BQ', '1', '28', 'Bonaire' ],
        [ 'BA', '3', '29', 'Bosnia and Herzegovina' ],
        [ 'BW', '4', '30', 'Botswana' ],
        [ 'BV', '1', '31', 'Bouvet Island' ],
        [ 'BR', '1', '32', 'Brazil' ],
        # [ 'IO', '', '33', 'British Indian Ocean Territory' ],
        [ 'BN', '2', '34', 'Brunei' ],
        [ 'BG', '3', '35', 'Bulgaria' ],
        [ 'BF', '4', '36', 'Burkina Faso' ],
        [ 'BI', '4', '37', 'Burundi' ],
        [ 'KH', '2', '38', 'Cambodia' ],
        [ 'CM', '4', '39', 'Cameroon' ],
        [ 'CA', '1', '40', 'Canada' ],
        [ 'CV', '4', '41', 'Cape Verde' ],
        [ 'KY', '1', '42', 'Cayman Islands' ],
        [ 'CF', '4', '43', 'Central African Republic' ],
        [ 'TD', '4', '44', 'Chad' ],
        [ 'CL', '1', '45', 'Chile' ],
        [ 'CN', '2', '46', 'China' ],
        [ 'CX', '2', '47', 'Christmas Island' ],
        [ 'CC', '2', '48', 'Cocos (Keeling) Islands' ],
        [ 'CO', '1', '49', 'Colombia' ],
        [ 'KM', '4', '50', 'Comoros' ],
        [ 'CG', '4', '51', 'Republic of the Congo' ],
        [ 'CD', '4', '52', 'Democratic Republic of the Congo' ],
        [ 'CK', '2', '53', 'Cook Islands' ],
        [ 'CR', '1', '54', 'Costa Rica' ],
        [ 'CI', '4', '55', 'Ivory Coast' ],
        [ 'HR', '3', '56', 'Croatia' ],
        [ 'CU', '1', '57', 'Cuba' ],
        [ 'CW', '1', '58', 'Curaçao' ],
        [ 'CY', '2', '59', 'Cyprus' ], # NOTE: 3
        [ 'CZ', '3', '60', 'Czech Republic' ],
        [ 'DK', '3', '61', 'Denmark' ],
        [ 'DJ', '4', '62', 'Djibouti' ],
        [ 'DM', '1', '63', 'Dominica' ],
        [ 'DO', '1', '64', 'Dominican Republic' ],
        [ 'EC', '1', '65', 'Ecuador' ],
        [ 'EG', '4', '66', 'Egypt' ],
        [ 'SV', '1', '67', 'El Salvador' ],
        [ 'GQ', '4', '68', 'Equatorial Guinea' ],
        [ 'ER', '4', '69', 'Eritrea' ],
        [ 'EE', '3', '70', 'Estonia' ],
        [ 'ET', '4', '71', 'Ethiopia' ],
        [ 'FK', '1', '72', 'Falkland Islands' ],
        [ 'FO', '3', '73', 'Faroe Islands' ],
        [ 'FJ', '2', '74', 'Fiji' ],
        [ 'FI', '3', '75', 'Finland' ],
        [ 'FR', '3', '76', 'France' ],
        [ 'GF', '1', '77', 'French Guiana' ],
        [ 'PF', '2', '78', 'French Polynesia' ],
        [ 'TF', '4', '79', 'French Southern and Antarctic Lands' ],
        [ 'GA', '4', '80', 'Gabon' ],
        [ 'GM', '4', '81', 'The Gambia' ],
        [ 'GE', '2', '82', 'Georgia' ], # NOTE: 3
        [ 'DE', '3', '83', 'Germany' ],
        [ 'GH', '4', '84', 'Ghana' ],
        [ 'GI', '3', '85', 'Gibraltar' ],
        [ 'GR', '3', '86', 'Greece' ],
        [ 'GL', '1', '87', 'Greenland' ], # group_id 3?
        [ 'GD', '1', '88', 'Grenada' ],
        [ 'GP', '1', '89', 'Guadeloupe' ],
        [ 'GU', '2', '90', 'Guam' ],
        [ 'GT', '1', '91', 'Guatemala' ],
        [ 'GG', '3', '92', 'Bailiwick of Guernsey' ],
        [ 'GN', '4', '93', 'Guinea' ],
        [ 'GW', '4', '94', 'Guinea-Bissau' ],
        [ 'GY', '1', '95', 'Guyana' ],
        [ 'HT', '1', '96', 'Haiti' ],
        [ 'HM', '2', '97', 'Heard Island and Mcdonald Islands' ],
        [ 'HN', '1', '99', 'Honduras' ],
        [ 'HK', '2', '100', 'Hong Kong' ],
        [ 'HU', '3', '101', 'Hungary' ],
        # [ 'IC', '4', '102', 'Canary Islands' ],
        [ 'IS', '3', '102', 'Iceland' ],
        [ 'IN', '2', '103', 'India' ],
        [ 'ID', '2', '104', 'Indonesia' ],
        [ 'IR', '2', '105', 'Iran' ],
        [ 'IQ', '2', '106', 'Iraq' ],
        [ 'IE', '3', '107', 'Ireland' ],
        [ 'IM', '3', '108', 'Isle of Man' ],
        [ 'IL', '2', '109', 'Israel' ],
        [ 'IT', '3', '110', 'Italy' ],
        [ 'JM', '1', '111', 'Jamaica' ],
        [ 'JP', '2', '112', 'Japan' ],
        [ 'JE', '3', '113', 'Jersey' ],
        [ 'JO', '2', '114', 'Jordan' ],
        [ 'KZ', '2', '115', 'Kazakhstan' ], # NOTE: 3
        [ 'KE', '4', '116', 'Kenya' ],
        [ 'KI', '2', '117', 'Kiribati' ],
        [ 'KP', '2', '118', 'North Korea' ],
        [ 'KR', '2', '119', 'South Korea' ],
        [ 'KW', '2', '120', 'Kuwait' ],
        [ 'KG', '2', '121', 'Kyrgyzstan' ],
        [ 'LA', '2', '122', 'Laos' ],
        [ 'LV', '3', '123', 'Latvia' ],
        [ 'LB', '2', '124', 'Lebanon' ],
        [ 'LS', '4', '125', 'Lesotho' ],
        [ 'LR', '4', '126', 'Liberia' ],
        [ 'LY', '4', '127', 'Libya' ],
        [ 'LI', '3', '128', 'Liechtenstein' ],
        [ 'LT', '3', '129', 'Lithuania' ],
        [ 'LU', '3', '130', 'Luxembourg' ],
        [ 'MO', '2', '131', 'Macao' ],
        [ 'MK', '3', '132', 'North Macedonia' ],
        [ 'MG', '4', '133', 'Madagascar' ],
        [ 'MW', '4', '134', 'Malawi' ],
        [ 'MY', '2', '135', 'Malaysia' ],
        [ 'MV', '2', '136', 'Maldives' ],
        [ 'ML', '4', '137', 'Mali' ],
        [ 'MT', '3', '138', 'Malta' ],
        [ 'MH', '2', '139', 'Marshall Islands' ],
        [ 'MQ', '1', '140', 'Martinique' ],
        [ 'MR', '4', '141', 'Mauritania' ],
        [ 'MU', '4', '142', 'Mauritius' ],
        [ 'YT', '4', '143', 'Mayotte' ],
        [ 'MX', '1', '144', 'Mexico' ],
        [ 'FM', '2', '145', 'Federated States of Micronesia' ],
        [ 'MD', '3', '146', 'Moldova' ],
        [ 'MC', '3', '147', 'Monaco' ],
        [ 'MN', '2', '148', 'Mongolia' ],
        [ 'ME', '3', '149', 'Montenegro' ],
        [ 'MS', '1', '150', 'Montserrat' ],
        [ 'MA', '4', '151', 'Morocco' ],
        [ 'MZ', '4', '152', 'Mozambique' ],
        [ 'MM', '2', '153', 'Myanmar' ],
        [ 'NA', '4', '154', 'Namibia' ],
        [ 'NR', '2', '155', 'Nauru' ],
        [ 'NP', '2', '156', 'Nepal' ],
        [ 'NL', '3', '157', 'Netherlands' ],
        [ 'NC', '2', '158', 'New Caledonia' ],
        [ 'NZ', '2', '159', 'New Zealand' ],
        [ 'NI', '1', '160', 'Nicaragua' ],
        [ 'NE', '4', '161', 'Niger' ],
        [ 'NG', '4', '162', 'Nigeria' ],
        [ 'NU', '2', '163', 'Niue' ],
        [ 'NF', '2', '164', 'Norfolk Island' ],
        [ 'MP', '2', '165', 'Northern Mariana Islands' ],
        [ 'NO', '3', '166', 'Norway' ],
        [ 'OM', '2', '167', 'Oman' ],
        [ 'PK', '2', '168', 'Pakistan' ],
        [ 'PW', '2', '169', 'Palau' ],
        [ 'PS', '2', '170', 'Palestine' ],
        [ 'PA', '1', '171', 'Panama' ],
        [ 'PG', '2', '172', 'Papua New Guinea' ],
        [ 'PY', '1', '173', 'Paraguay' ],
        [ 'PE', '1', '174', 'Peru' ],
        [ 'PH', '2', '175', 'Philippines' ],
        [ 'PN', '2', '176', 'Pitcairn Islands' ],
        [ 'PL', '3', '177', 'Poland' ],
        [ 'PT', '3', '178', 'Portugal' ],
        [ 'PR', '1', '179', 'Puerto Rico' ],
        [ 'QA', '2', '180', 'Qatar' ],
        [ 'RE', '4', '181', 'Réunion' ],
        [ 'RO', '3', '182', 'Romania' ],
        [ 'RU', '3', '183', 'Russia' ], # NOTE: 2
        [ 'RW', '4', '184', 'Rwanda' ],
        [ 'BL', '1', '185', 'Saint Barthélemy' ],
        [ 'SH', '4', '186', 'Saint Helena, Ascension and Tristan da Cunha' ],
        [ 'KN', '1', '187', 'Saint Kitts and Nevis' ],
        [ 'LC', '1', '188', 'Saint Lucia' ],
        [ 'MF', '1', '189', 'Saint Martin' ],
        [ 'PM', '1', '190', 'Saint Pierre and Miquelon' ],
        [ 'VC', '1', '191', 'Saint Vincent and the Grenadines' ],
        [ 'WS', '2', '192', 'Samoa' ],
        [ 'SM', '3', '193', 'San Marino' ],
        [ 'ST', '4', '194', 'São Tomé and Príncipe' ],
        [ 'SA', '2', '195', 'Saudi Arabia' ],
        [ 'SN', '4', '196', 'Senegal' ],
        [ 'RS', '3', '197', 'Serbia' ],
        [ 'SC', '4', '198', 'Seychelles' ],
        [ 'SL', '4', '199', 'Sierra Leone' ],
        [ 'SG', '2', '200', 'Singapore' ],
        [ 'SX', '1', '201', 'Sint Maarten' ],
        [ 'SK', '3', '202', 'Slovakia' ],
        [ 'SI', '3', '203', 'Slovenia' ],
        [ 'SB', '2', '204', 'Solomon Islands' ],
        [ 'SO', '4', '205', 'Somalia' ],
        [ 'ZA', '4', '206', 'South Africa' ],
        [ 'GS', '1', '207', 'South Georgia and the South Sandwich Islands' ],
        [ 'SS', '4', '208', 'South Sudan' ],
        [ 'ES', '3', '209', 'Spain' ],
        [ 'LK', '2', '210', 'Sri Lanka' ],
        [ 'SD', '4', '211', 'Sudan' ],
        [ 'SR', '1', '212', 'Suriname' ],
        [ 'SJ', '3', '213', 'Svalbard and Jan Mayen' ],
        [ 'SZ', '4', '214', 'Eswatini' ],
        [ 'SE', '3', '215', 'Sweden' ],
        [ 'CH', '3', '216', 'Switzerland' ],
        [ 'SY', '2', '217', 'Syria' ],
        [ 'TW', '2', '218', 'Taiwan' ],
        [ 'TJ', '2', '219', 'Tajikistan' ],
        [ 'TZ', '4', '220', 'Tanzania,' ],
        [ 'TH', '2', '221', 'Thailand' ],
        [ 'TL', '2', '222', 'East Timor' ],
        [ 'TG', '4', '223', 'Togo' ],
        [ 'TK', '2', '224', 'Tokelau' ],
        [ 'TO', '2', '225', 'Tonga' ],
        [ 'TT', '1', '226', 'Trinidad and Tobago' ],
        [ 'TN', '4', '227', 'Tunisia' ],
        [ 'TR', '3', '228', 'Turkey' ], # NOTE: 2
        [ 'TM', '2', '229', 'Turkmenistan' ],
        [ 'TC', '1', '230', 'Turks and Caicos Islands' ],
        [ 'TV', '2', '231', 'Tuvalu' ],
        [ 'UG', '4', '232', 'Uganda' ],
        [ 'UA', '3', '233', 'Ukraine' ],
        [ 'AE', '2', '234', 'United Arab Emirates' ],
        [ 'GB', '3', '235', 'United Kingdom' ],
        [ 'US', '1', '236', 'United States' ],
        [ 'UM', '2', '237', 'United States Minor Outlying Islands' ],
        [ 'UY', '1', '238', 'Uruguay' ],
        [ 'UZ', '2', '239', 'Uzbekistan' ],
        [ 'VA', '3', '98', 'Vatican City State' ],
        [ 'VU', '2', '240', 'Vanuatu' ],
        [ 'VE', '1', '241', 'Venezuela' ],
        [ 'VN', '2', '242', 'Viet Nam' ],
        [ 'VG', '1', '243', 'British Virgin Islands' ],
        [ 'VI', '1', '244', 'United States Virgin Islands' ],
        [ 'WF', '2', '245', 'Wallis and Futuna' ],
        [ 'EH', '4', '246', 'Western Sahara' ],
        [ 'YE', '2', '247', 'Yemen' ],
        [ 'ZM', '4', '248', 'Zambia' ],
        [ 'ZW', '4', '249', 'Zimbabwe' ],
    ],
)
