(
    'AddressContinent' => [
        [qw/id position name/],
        [ '1', '1', 'Americas' ],
        [ '2', '2', 'Asia Pacific' ],
        [ '3', '3', 'Europe' ],
        [ '4', '4', 'Africa' ],
    ],

    # ISO 3166-1 alpha-2 code and english name
    'AddressCountry' => [
        [qw/code group_id is_actived position name/],
        [ 'AF', '2', 0, '1', 'Afghanistan' ],
        [ 'AX', '3', 0, '2', 'Åland Islands' ],
        [ 'AL', '3', 0, '3', 'Albania' ],
        [ 'DZ', '4', 0, '4', 'Algeria' ],
        [ 'AS', '2', 0, '5', 'American Samoa' ],
        [ 'AD', '3', 0, '6', 'Andorra' ],
        [ 'AO', '4', 0, '7', 'Angola' ],
        [ 'AI', '1', 0, '8', 'Anguilla' ],
        # [ 'AQ', '', 0, '9', 'Antarctica' ], # 南極
        [ 'AG', '1', 0, '10', 'Antigua and Barbuda' ],
        [ 'AR', '1', 0, '11', 'Argentina' ],
        [ 'AM', '2', 0, '12', 'Armenia' ], # NOTE: 3
        [ 'AW', '1', 0, '13', 'Aruba' ],
        [ 'AU', '2', 0, '14', 'Australia' ],
        [ 'AT', '3', 0, '15', 'Austria' ],
        [ 'AZ', '2', 0, '16', 'Azerbaijan' ], # NOTE: 3
        [ 'BS', '1', 0, '17', 'Bahamas' ],
        [ 'BH', '2', 0, '18', 'Bahrain' ],
        [ 'BD', '2', 0, '19', 'Bangladesh' ],
        [ 'BB', '1', 0, '20', 'Barbados' ],
        [ 'BY', '3', 0, '21', 'Belarus' ],
        [ 'BE', '3', 0, '22', 'Belgium' ],
        [ 'BZ', '1', 0, '23', 'Belize' ],
        [ 'BJ', '4', 0, '24', 'Benin' ],
        [ 'BM', '1', 0, '25', 'Bermuda' ],
        [ 'BT', '2', 0, '26', 'Bhutan' ],
        [ 'BO', '1', 0, '27', 'Bolivia' ],
        [ 'BQ', '1', 0, '28', 'Bonaire' ],
        [ 'BA', '3', 0, '29', 'Bosnia and Herzegovina' ],
        [ 'BW', '4', 0, '30', 'Botswana' ],
        [ 'BV', '1', 0, '31', 'Bouvet Island' ],
        [ 'BR', '1', 0, '32', 'Brazil' ],
        # [ 'IO', '', 0, '33', 'British Indian Ocean Territory' ],
        [ 'BN', '2', 0, '34', 'Brunei' ],
        [ 'BG', '3', 0, '35', 'Bulgaria' ],
        [ 'BF', '4', 0, '36', 'Burkina Faso' ],
        [ 'BI', '4', 0, '37', 'Burundi' ],
        [ 'KH', '2', 0, '38', 'Cambodia' ],
        [ 'CM', '4', 0, '39', 'Cameroon' ],
        [ 'CA', '1', 1, '40', 'Canada' ],
        [ 'CV', '4', 0, '41', 'Cape Verde' ],
        [ 'KY', '1', 0, '42', 'Cayman Islands' ],
        [ 'CF', '4', 0, '43', 'Central African Republic' ],
        [ 'TD', '4', 0, '44', 'Chad' ],
        [ 'CL', '1', 0, '45', 'Chile' ],
        [ 'CN', '2', 1, '46', 'China' ],
        [ 'CX', '2', 0, '47', 'Christmas Island' ],
        [ 'CC', '2', 0, '48', 'Cocos (Keeling) Islands' ],
        [ 'CO', '1', 0, '49', 'Colombia' ],
        [ 'KM', '4', 0, '50', 'Comoros' ],
        [ 'CG', '4', 0, '51', 'Republic of the Congo' ],
        [ 'CD', '4', 0, '52', 'Democratic Republic of the Congo' ],
        [ 'CK', '2', 0, '53', 'Cook Islands' ],
        [ 'CR', '1', 0, '54', 'Costa Rica' ],
        [ 'CI', '4', 0, '55', 'Ivory Coast' ],
        [ 'HR', '3', 0, '56', 'Croatia' ],
        [ 'CU', '1', 0, '57', 'Cuba' ],
        [ 'CW', '1', 0, '58', 'Curaçao' ],
        [ 'CY', '2', 0, '59', 'Cyprus' ], # NOTE: 3
        [ 'CZ', '3', 0, '60', 'Czech Republic' ],
        [ 'DK', '3', 0, '61', 'Denmark' ],
        [ 'DJ', '4', 0, '62', 'Djibouti' ],
        [ 'DM', '1', 0, '63', 'Dominica' ],
        [ 'DO', '1', 0, '64', 'Dominican Republic' ],
        [ 'EC', '1', 0, '65', 'Ecuador' ],
        [ 'EG', '4', 0, '66', 'Egypt' ],
        [ 'SV', '1', 0, '67', 'El Salvador' ],
        [ 'GQ', '4', 0, '68', 'Equatorial Guinea' ],
        [ 'ER', '4', 0, '69', 'Eritrea' ],
        [ 'EE', '3', 0, '70', 'Estonia' ],
        [ 'ET', '4', 0, '71', 'Ethiopia' ],
        [ 'FK', '1', 0, '72', 'Falkland Islands' ],
        [ 'FO', '3', 0, '73', 'Faroe Islands' ],
        [ 'FJ', '2', 0, '74', 'Fiji' ],
        [ 'FI', '3', 0, '75', 'Finland' ],
        [ 'FR', '3', 0, '76', 'France' ],
        [ 'GF', '1', 0, '77', 'French Guiana' ],
        [ 'PF', '2', 0, '78', 'French Polynesia' ],
        [ 'TF', '4', 0, '79', 'French Southern and Antarctic Lands' ],
        [ 'GA', '4', 0, '80', 'Gabon' ],
        [ 'GM', '4', 0, '81', 'The Gambia' ],
        [ 'GE', '2', 0, '82', 'Georgia' ], # NOTE: 3
        [ 'DE', '3', 1, '83', 'Germany' ],
        [ 'GH', '4', 0, '84', 'Ghana' ],
        [ 'GI', '3', 0, '85', 'Gibraltar' ],
        [ 'GR', '3', 0, '86', 'Greece' ],
        [ 'GL', '1', 0, '87', 'Greenland' ], # group_id 3?
        [ 'GD', '1', 0, '88', 'Grenada' ],
        [ 'GP', '1', 0, '89', 'Guadeloupe' ],
        [ 'GU', '2', 0, '90', 'Guam' ],
        [ 'GT', '1', 0, '91', 'Guatemala' ],
        [ 'GG', '3', 0, '92', 'Bailiwick of Guernsey' ],
        [ 'GN', '4', 0, '93', 'Guinea' ],
        [ 'GW', '4', 0, '94', 'Guinea-Bissau' ],
        [ 'GY', '1', 0, '95', 'Guyana' ],
        [ 'HT', '1', 0, '96', 'Haiti' ],
        [ 'HM', '2', 0, '97', 'Heard Island and Mcdonald Islands' ],
        [ 'HN', '1', 0, '99', 'Honduras' ],
        [ 'HK', '2', 0, '100', 'Hong Kong' ],
        [ 'HU', '3', 0, '101', 'Hungary' ],
        # [ 'IC', '4', 0, '102', 'Canary Islands' ],
        [ 'IS', '3', 0, '102', 'Iceland' ],
        [ 'IN', '2', 0, '103', 'India' ],
        [ 'ID', '2', 0, '104', 'Indonesia' ],
        [ 'IR', '2', 0, '105', 'Iran' ],
        [ 'IQ', '2', 0, '106', 'Iraq' ],
        [ 'IE', '3', 0, '107', 'Ireland' ],
        [ 'IM', '3', 0, '108', 'Isle of Man' ],
        [ 'IL', '2', 0, '109', 'Israel' ],
        [ 'IT', '3', 0, '110', 'Italy' ],
        [ 'JM', '1', 0, '111', 'Jamaica' ],
        [ 'JP', '2', 1, '112', 'Japan' ],
        [ 'JE', '3', 0, '113', 'Jersey' ],
        [ 'JO', '2', 0, '114', 'Jordan' ],
        [ 'KZ', '2', 0, '115', 'Kazakhstan' ], # NOTE: 3
        [ 'KE', '4', 0, '116', 'Kenya' ],
        [ 'KI', '2', 0, '117', 'Kiribati' ],
        [ 'KP', '2', 0, '118', 'North Korea' ],
        [ 'KR', '2', 0, '119', 'South Korea' ],
        [ 'KW', '2', 0, '120', 'Kuwait' ],
        [ 'KG', '2', 0, '121', 'Kyrgyzstan' ],
        [ 'LA', '2', 0, '122', 'Laos' ],
        [ 'LV', '3', 0, '123', 'Latvia' ],
        [ 'LB', '2', 0, '124', 'Lebanon' ],
        [ 'LS', '4', 0, '125', 'Lesotho' ],
        [ 'LR', '4', 0, '126', 'Liberia' ],
        [ 'LY', '4', 0, '127', 'Libya' ],
        [ 'LI', '3', 0, '128', 'Liechtenstein' ],
        [ 'LT', '3', 0, '129', 'Lithuania' ],
        [ 'LU', '3', 0, '130', 'Luxembourg' ],
        [ 'MO', '2', 0, '131', 'Macao' ],
        [ 'MK', '3', 0, '132', 'North Macedonia' ],
        [ 'MG', '4', 0, '133', 'Madagascar' ],
        [ 'MW', '4', 0, '134', 'Malawi' ],
        [ 'MY', '2', 0, '135', 'Malaysia' ],
        [ 'MV', '2', 0, '136', 'Maldives' ],
        [ 'ML', '4', 0, '137', 'Mali' ],
        [ 'MT', '3', 0, '138', 'Malta' ],
        [ 'MH', '2', 0, '139', 'Marshall Islands' ],
        [ 'MQ', '1', 0, '140', 'Martinique' ],
        [ 'MR', '4', 0, '141', 'Mauritania' ],
        [ 'MU', '4', 0, '142', 'Mauritius' ],
        [ 'YT', '4', 0, '143', 'Mayotte' ],
        [ 'MX', '1', 0, '144', 'Mexico' ],
        [ 'FM', '2', 0, '145', 'Federated States of Micronesia' ],
        [ 'MD', '3', 0, '146', 'Moldova' ],
        [ 'MC', '3', 0, '147', 'Monaco' ],
        [ 'MN', '2', 0, '148', 'Mongolia' ],
        [ 'ME', '3', 0, '149', 'Montenegro' ],
        [ 'MS', '1', 0, '150', 'Montserrat' ],
        [ 'MA', '4', 0, '151', 'Morocco' ],
        [ 'MZ', '4', 0, '152', 'Mozambique' ],
        [ 'MM', '2', 0, '153', 'Myanmar' ],
        [ 'NA', '4', 0, '154', 'Namibia' ],
        [ 'NR', '2', 0, '155', 'Nauru' ],
        [ 'NP', '2', 0, '156', 'Nepal' ],
        [ 'NL', '3', 0, '157', 'Netherlands' ],
        [ 'NC', '2', 0, '158', 'New Caledonia' ],
        [ 'NZ', '2', 0, '159', 'New Zealand' ],
        [ 'NI', '1', 0, '160', 'Nicaragua' ],
        [ 'NE', '4', 0, '161', 'Niger' ],
        [ 'NG', '4', 1, '162', 'Nigeria' ],
        [ 'NU', '2', 0, '163', 'Niue' ],
        [ 'NF', '2', 0, '164', 'Norfolk Island' ],
        [ 'MP', '2', 0, '165', 'Northern Mariana Islands' ],
        [ 'NO', '3', 0, '166', 'Norway' ],
        [ 'OM', '2', 0, '167', 'Oman' ],
        [ 'PK', '2', 0, '168', 'Pakistan' ],
        [ 'PW', '2', 0, '169', 'Palau' ],
        [ 'PS', '2', 0, '170', 'Palestine' ],
        [ 'PA', '1', 0, '171', 'Panama' ],
        [ 'PG', '2', 0, '172', 'Papua New Guinea' ],
        [ 'PY', '1', 0, '173', 'Paraguay' ],
        [ 'PE', '1', 0, '174', 'Peru' ],
        [ 'PH', '2', 0, '175', 'Philippines' ],
        [ 'PN', '2', 0, '176', 'Pitcairn Islands' ],
        [ 'PL', '3', 0, '177', 'Poland' ],
        [ 'PT', '3', 0, '178', 'Portugal' ],
        [ 'PR', '1', 0, '179', 'Puerto Rico' ],
        [ 'QA', '2', 0, '180', 'Qatar' ],
        [ 'RE', '4', 0, '181', 'Réunion' ],
        [ 'RO', '3', 0, '182', 'Romania' ],
        [ 'RU', '3', 0, '183', 'Russia' ], # NOTE: 2
        [ 'RW', '4', 0, '184', 'Rwanda' ],
        [ 'BL', '1', 0, '185', 'Saint Barthélemy' ],
        [ 'SH', '4', 0, '186', 'Saint Helena, Ascension and Tristan da Cunha' ],
        [ 'KN', '1', 0, '187', 'Saint Kitts and Nevis' ],
        [ 'LC', '1', 0, '188', 'Saint Lucia' ],
        [ 'MF', '1', 0, '189', 'Saint Martin' ],
        [ 'PM', '1', 0, '190', 'Saint Pierre and Miquelon' ],
        [ 'VC', '1', 0, '191', 'Saint Vincent and the Grenadines' ],
        [ 'WS', '2', 0, '192', 'Samoa' ],
        [ 'SM', '3', 0, '193', 'San Marino' ],
        [ 'ST', '4', 0, '194', 'São Tomé and Príncipe' ],
        [ 'SA', '2', 0, '195', 'Saudi Arabia' ],
        [ 'SN', '4', 0, '196', 'Senegal' ],
        [ 'RS', '3', 0, '197', 'Serbia' ],
        [ 'SC', '4', 0, '198', 'Seychelles' ],
        [ 'SL', '4', 0, '199', 'Sierra Leone' ],
        [ 'SG', '2', 0, '200', 'Singapore' ],
        [ 'SX', '1', 0, '201', 'Sint Maarten' ],
        [ 'SK', '3', 0, '202', 'Slovakia' ],
        [ 'SI', '3', 0, '203', 'Slovenia' ],
        [ 'SB', '2', 0, '204', 'Solomon Islands' ],
        [ 'SO', '4', 0, '205', 'Somalia' ],
        [ 'ZA', '4', 1, '206', 'South Africa' ],
        [ 'GS', '1', 0, '207', 'South Georgia and the South Sandwich Islands' ],
        [ 'SS', '4', 0, '208', 'South Sudan' ],
        [ 'ES', '3', 0, '209', 'Spain' ],
        [ 'LK', '2', 0, '210', 'Sri Lanka' ],
        [ 'SD', '4', 0, '211', 'Sudan' ],
        [ 'SR', '1', 0, '212', 'Suriname' ],
        [ 'SJ', '3', 0, '213', 'Svalbard and Jan Mayen' ],
        [ 'SZ', '4', 0, '214', 'Eswatini' ],
        [ 'SE', '3', 0, '215', 'Sweden' ],
        [ 'CH', '3', 0, '216', 'Switzerland' ],
        [ 'SY', '2', 0, '217', 'Syria' ],
        [ 'TW', '2', 0, '218', 'Taiwan' ],
        [ 'TJ', '2', 0, '219', 'Tajikistan' ],
        [ 'TZ', '4', 0, '220', 'Tanzania,' ],
        [ 'TH', '2', 0, '221', 'Thailand' ],
        [ 'TL', '2', 0, '222', 'East Timor' ],
        [ 'TG', '4', 0, '223', 'Togo' ],
        [ 'TK', '2', 0, '224', 'Tokelau' ],
        [ 'TO', '2', 0, '225', 'Tonga' ],
        [ 'TT', '1', 0, '226', 'Trinidad and Tobago' ],
        [ 'TN', '4', 0, '227', 'Tunisia' ],
        [ 'TR', '3', 0, '228', 'Turkey' ], # NOTE: 2
        [ 'TM', '2', 0, '229', 'Turkmenistan' ],
        [ 'TC', '1', 0, '230', 'Turks and Caicos Islands' ],
        [ 'TV', '2', 0, '231', 'Tuvalu' ],
        [ 'UG', '4', 0, '232', 'Uganda' ],
        [ 'UA', '3', 0, '233', 'Ukraine' ],
        [ 'AE', '2', 0, '234', 'United Arab Emirates' ],
        [ 'GB', '3', 1, '235', 'United Kingdom' ],
        [ 'US', '1', 1, '236', 'United States' ],
        [ 'UM', '2', 0, '237', 'United States Minor Outlying Islands' ],
        [ 'UY', '1', 0, '238', 'Uruguay' ],
        [ 'UZ', '2', 0, '239', 'Uzbekistan' ],
        [ 'VA', '3', 0, '98', 'Vatican City State' ],
        [ 'VU', '2', 0, '240', 'Vanuatu' ],
        [ 'VE', '1', 0, '241', 'Venezuela' ],
        [ 'VN', '2', 0, '242', 'Viet Nam' ],
        [ 'VG', '1', 0, '243', 'British Virgin Islands' ],
        [ 'VI', '1', 0, '244', 'United States Virgin Islands' ],
        [ 'WF', '2', 0, '245', 'Wallis and Futuna' ],
        [ 'EH', '4', 0, '246', 'Western Sahara' ],
        [ 'YE', '2', 0, '247', 'Yemen' ],
        [ 'ZM', '4', 0, '248', 'Zambia' ],
        [ 'ZW', '4', 0, '249', 'Zimbabwe' ],
    ],
)
