#!/usr/bin/env perl

use Mojo::Base -strict;
use File::Spec;
use File::Basename;
use lib File::Spec->catdir( dirname(__FILE__), '..', 'lib' );
use Mojo::File qw/path/;

use Markets::Schema;
use Markets::App::Common;
use Markets::Install::Util;

my $conf = Markets::Install::Util::load_config();

# Deploy schema
my $dsn    = Markets::App::Common::_dsn( $conf->{db} );
my $schema = Markets::Schema->connect($dsn);
$schema->deploy( { add_drop_table => 1 } );

# Insert data
my $base_dir = path( dirname(__FILE__), '..', 'share' );
my @paths;
push @paths, ( path( $base_dir, 'default_data.pl' ), path( $base_dir, 'test_data.pl' ) );

foreach my $path (@paths) {
    eval { Markets::Install::Util::insert_data( $schema, $path ) };
    die $@ if $@;
}

say 'All process completed.';
exit;

__END__

=head1 NAME

=head1 SYNOPSIS

    perl script/deploy_schema

    # MOJO_MODE=production
    perl script/deploy_schema -mode production


=head1 DESCRIPTION

=head1 AUTHOR

Markets authors.
