#!/usr/bin/env perl

use Mojo::Base -strict;
use File::Spec;
use File::Basename;
use lib File::Spec->catdir( dirname(__FILE__), '..', 'lib' );
use Mojo::File qw/path/;

use Yetie::Schema;
use Yetie::App::Common;
use Yetie::Install::Util;

# Deploy schema
my $conf   = Yetie::Install::Util::load_config();
my $app    = Yetie::App::Common->new( config => $conf );
my $schema = $app->schema;
$schema->deploy( { add_drop_table => 1 } );

# Insert data
my $base_dir = path( dirname(__FILE__), '..', 'share' );
my @paths;
push @paths,
  (
    path( $base_dir, 'default_data.pl' ),
    path( $base_dir, 'address_country_iso_3166_1.pl' ),
    path( $base_dir, 'sample_addon_data.pl' ),
    path( $base_dir, 'sample_data.pl' ),
  );

foreach my $path (@paths) {
    eval { Yetie::Install::Util::insert_data( $schema, $path ) };
    die $@ if $@;
}

say 'All process completed.';
exit;

__END__

=head1 NAME

=head1 SYNOPSIS

    perl script/deploy_schema

    # MOJO_MODE=production
    perl script/deploy_schema -mode production


=head1 DESCRIPTION

=head1 AUTHOR

Yetie authors.
