-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 18:17:19 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema markets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema markets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `markets` DEFAULT CHARACTER SET utf8mb4 ;
USE `markets` ;

-- -----------------------------------------------------
-- Table `markets`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`sessions` (
  `sid` VARCHAR(40) NOT NULL COMMENT '',
  `data` LONGTEXT NULL COMMENT '',
  `expires` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`sid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markets`.`constants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`constants` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `default_value` TEXT NULL COMMENT '',
  `value` TEXT NULL COMMENT '',
  `summary` TEXT NULL COMMENT '',
  `category` INT NULL COMMENT '',
  `position` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markets`.`constant_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`constant_categories` (
  `constant_categories_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`constant_categories_id`)  COMMENT '');

USE `markets` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `markets`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
