-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 19:31:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema markets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema markets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `markets` DEFAULT CHARACTER SET utf8mb4 ;
USE `markets` ;

-- -----------------------------------------------------
-- Table `markets`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`sessions` (
  `sid` VARCHAR(50) NOT NULL COMMENT '',
  `data` MEDIUMTEXT NULL COMMENT '',
  `cart_id` VARCHAR(50) NULL COMMENT '',
  `expires` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`sid`)  COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `markets`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`carts` (
  `cart_id` VARCHAR(50) NOT NULL COMMENT '',
  `data` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`cart_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markets`.`constants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`constants` (
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `default_value` TEXT NULL COMMENT '',
  `value` TEXT NULL COMMENT '',
  `summary` TEXT NULL COMMENT '',
  `label` INT NULL COMMENT '',
  `position` INT NULL COMMENT '',
  PRIMARY KEY (`name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markets`.`constant_labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`constant_labels` (
  `constant_label_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`constant_label_id`)  COMMENT '');


-- -----------------------------------------------------
-- Table `markets`.`addons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`addons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(70) NOT NULL COMMENT '',
  `is_enabled` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markets`.`addons_hooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets`.`addons_hooks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `addon_id` INT UNSIGNED NOT NULL COMMENT '',
  `hook_name` VARCHAR(45) NOT NULL COMMENT '',
  `priority` INT UNSIGNED NOT NULL DEFAULT 100 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_addons_hooks_addons_idx` (`addon_id` ASC)  COMMENT '',
  CONSTRAINT `fk_addons_hooks_addons`
    FOREIGN KEY (`addon_id`)
    REFERENCES `markets`.`addons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
